sources:
  - AdventPro.designspace
axisOrder:
  - wdth
  - wght
  - ital
familyName: Advent Pro

includeSourceFixes: true
buildOTF: false
buildTTF: true
buildWebfont: false
buildStatic: false
buildVariable: true
